### ISSUE TITLE
Configurar UEFI en lloc de BIOS a VMWare Workstation a Windows

### ISSUE THREAD

**Issue by JordiMateoUdL** [AMSA-2425-GEI-UDL/laboratoris#8]
**Descripció:**
De manera predeterminada, VMWare Workstation utilitza BIOS per a les màquines virtuals en entorns Windows.

**Tasca:**
Documentar els passos detallats per crear una màquina virtual amb VMWare Workstation a Windows utilitzant UEFI en lloc de BIOS.

**Comment by polMarsol** [comment]
## RESOLT
### Requisits
- Tenir VMWare Workstation instal·lat.
- La màquina virtual (VM) ha d'estar apagada abans de començar el procés. 

### Resolució

#### -> Pas 1
-  Obrir Settings (`Control + D`).
<img width="562" alt="image" src="https://github.com/user-attachments/assets/1b93422c-2915-4571-8bc0-3c5925fcff3e">


- Accedir a Options. 
<img width="557" alt="image" src="https://github.com/user-attachments/assets/feee0ad9-e73c-4e8e-abd6-44c69f2f26e5">


- Cliquem a General i canviem el Guest Operating System a Microsoft Windows.
<img width="307" alt="image" src="https://github.com/user-attachments/assets/599383aa-94d3-4c52-a8a2-5f7222890e23">

#### -> Pas 2
- Accedir a Advanced. 
<img width="560" alt="image" src="https://github.com/user-attachments/assets/5f32cf08-4c4b-4c74-8705-08865968ed45">


- Cal canviar el Firmware Type de BIOS a UEFI (enable secure boot). 
<img width="310" alt="image" src="https://github.com/user-attachments/assets/7a3a1ec7-2ced-43fa-a60c-3c73913d1f42">


#### -> Pas 3
- Desar els canvis (`OK`).
<img width="185" alt="image" src="https://github.com/user-attachments/assets/81d02adf-2d9d-43fe-a3f4-49875fc1a7cf">


#### -> Pas 4
- Reinstalar la VM si fés falta (opcional).
<img width="636" alt="image" src="https://github.com/user-attachments/assets/7f921722-cc30-4d47-a3a3-d2d0c6058c8a">

---
**Documentació creada per:** 
*Pol Marsol*


`30 de septiembre de 2024`
---

**Comment by JordiMateoUdL** [comment]
Good job!
